### PR TITLE
fixes for 3.5 ?

### PR DESCRIPTION
**Pull request by danmarsden**
Just noticed a comment from Nadav in the plugins db, pointing at Darko's repo - I haven't reviewed this but filing a pull request so this ends up in our queue to look at.

### CODE REVIEW

**Comment by brendanheywood** [comment]
@kiklop74 can you please shed some light on the intent of $CFG->auth_enrolkey_legacy preferably in the form of changes to the README.

Also we are very open to pull requests, so please make issues / pr's

**Comment by kiklop74** [comment]
The first [commit](https://github.com/catalyst/moodle-auth_enrolkey/pull/20/commits/3c4eb0cc86e7f99c3aeba94acf0cc45101447e73) is a direct fix for the issue https://github.com/catalyst/moodle-auth_enrolkey/issues/15

The other fixes are related to a some bug behavior I can not recall right now. When I do I will write it in readme.

**Comment by davidpesce** [comment]
Any word on this? I'm running a Moodle (v3.3+) instance with the render error.

@kiklop74 - are you running this in production?

**Comment by davidpesce** [comment]
I can confirm that simply adding the renderer.php from @kiklop74 does resolve the render error and the login/create account page displays again. I did not apply the other fixes. Hopefully, that provides a data point in getting this into master.

**Comment by Peterburnett** [comment]
Hi all
thanks @kiklop74 for the renderer patch. I have copied the commits from this PR into #23, and changed the way that the emails are handled from an admin side. I'm going to close this PR, and work on getting #23 merged in ASAP

**Pull request closed without merging**
